#!/usr/bin/env node
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const readline = require('readline');

const CRED_DIR  = path.join(os.homedir(), '.config', 'cos-mcp');
const CRED_FILE = path.join(CRED_DIR, 'credentials');

const c = {
  bold:  s => `\x1b[1m${s}\x1b[0m`,
  dim:   s => `\x1b[2m${s}\x1b[0m`,
  green: s => `\x1b[32m${s}\x1b[0m`,
  red:   s => `\x1b[31m${s}\x1b[0m`,
  cyan:  s => `\x1b[36m${s}\x1b[0m`,
};

function ask(prompt, defaultVal) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const hint = defaultVal ? ` [默认: ${defaultVal}]` : '';
  return new Promise(r => rl.question(`${prompt}${hint}: `, a => {
    rl.close();
    r(a.trim() || defaultVal || '');
  }));
}

function askHidden(prompt) {
  return new Promise((resolve, reject) => {
    process.stdout.write(prompt + ': ');
    if (!process.stdin.isTTY) {
      const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
      rl.question('', a => { rl.close(); resolve(a.trim()); });
      return;
    }
    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    let val = '';
    const onData = ch => {
      if (ch === '') { process.stdout.write('\n'); process.stdin.setRawMode(false); process.stdin.pause(); process.stdin.removeListener('data', onData); reject(new Error('Cancelled')); }
      else if (ch === '\r' || ch === '\n' || ch === '') { process.stdout.write('\n'); process.stdin.setRawMode(false); process.stdin.pause(); process.stdin.removeListener('data', onData); resolve(val); }
      else if (ch === '' || ch === '\b') { if (val.length) val = val.slice(0, -1); }
      else { val += ch; }
    };
    process.stdin.on('data', onData);
  });
}

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--secret-id'  && argv[i+1]) { args.secretId  = argv[++i]; }
    else if (a === '--secret-key' && argv[i+1]) { args.secretKey = argv[++i]; }
    else if (a === '--bucket'     && argv[i+1]) { args.bucket    = argv[++i]; }
    else if (a === '--region'     && argv[i+1]) { args.region    = argv[++i]; }
  }
  return args;
}

(async () => {
  const cli = parseArgs(process.argv.slice(2));
  const nonInteractive = !!(cli.secretId && cli.secretKey && cli.bucket);

  console.log('');
  console.log(c.bold(c.cyan('◆ cos-mcp — 配置向导')));
  console.log(c.dim('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log('需要：腾讯云子账号 SecretId / SecretKey + COS bucket 名称\n');

  let secretId, secretKey, bucket, region;
  if (nonInteractive) {
    secretId  = cli.secretId;
    secretKey = cli.secretKey;
    bucket    = cli.bucket;
    region    = cli.region || 'ap-shanghai';
    console.log(c.dim(`非交互模式：bucket=${bucket}，region=${region}`));
  } else {
    try {
      secretId  = await askHidden('COS_SECRET_ID  （子账号 SecretId）');
      secretKey = await askHidden('COS_SECRET_KEY （子账号 SecretKey）');
      bucket    = await ask('COS_BUCKET     （如 my-bucket-1256981397）');
      region    = await ask('COS_REGION', 'ap-shanghai');
    } catch (e) {
      console.log(c.red('\n已取消。'));
      process.exit(1);
    }
  }

  if (!secretId || !secretKey || !bucket) {
    console.log(c.red('SecretId / SecretKey / Bucket 均不能为空。'));
    process.exit(1);
  }

  fs.mkdirSync(CRED_DIR, { recursive: true });
  const content = `# cos-mcp credentials — generated by setup.js on ${new Date().toISOString()}\n`
    + `COS_SECRET_ID=${secretId}\n`
    + `COS_SECRET_KEY=${secretKey}\n`
    + `COS_BUCKET=${bucket}\n`
    + `COS_REGION=${region}\n`
    + `COS_PREFIX=tmp\n`;
  fs.writeFileSync(CRED_FILE, content, { mode: 0o600 });

  console.log('');
  console.log(c.bold(c.green('✅ cos-mcp 配置完成')));
  console.log(c.dim(`凭据已写入：${CRED_FILE}`));
  console.log(c.dim('运行 /reload-plugins 后 cos MCP 即可用'));
  console.log('');
})().catch(e => { console.error(c.red('\n脚本异常：'), e); process.exit(1); });
