#!/usr/bin/env node
/**
 * oldoa-mcp — OAuth 授权配置
 *
 * 使用共享应用 Claude-etz（APP_KEY 已内置），无需自建应用。
 * 首次运行：输入 APP_SECRET → 浏览器授权 → 存 access_token
 * 后续 token 过期：直接重跑，跳过 APP_SECRET 输入。
 */
'use strict';

const fs = require('fs');
const path = require('path');
const os = require('os');
const https = require('https');
const readline = require('readline');
const { spawn } = require('child_process');


const CONFIG_DIR = process.env.OLDOA_CONFIG_DIR
  ? path.resolve(process.env.OLDOA_CONFIG_DIR.replace(/^~/, os.homedir()))
  : path.join(os.homedir(), '.config', 'oldoa');
const ENV_FILE = path.join(CONFIG_DIR, '.env');
const SECRETS_FILE = path.join(CONFIG_DIR, '.secrets.json');

const FIXED_APP_KEY = 'D1C31A867CAA';   // Claude-etz（共享应用，无需自建）
const FIXED_APP_NAME = 'Claude-etz';
const DEFAULT_CALLBACK_URL = 'http://localhost/callback';
const MINGDAO_API = 'https://api.mingdao.com';

// ── ANSI colors ─────────────────────────────────────────────────────────────
const c = {
  bold: s => `\x1b[1m${s}\x1b[0m`,
  dim:  s => `\x1b[2m${s}\x1b[0m`,
  green:s => `\x1b[32m${s}\x1b[0m`,
  red:  s => `\x1b[31m${s}\x1b[0m`,
  cyan: s => `\x1b[36m${s}\x1b[0m`,
  yellow:s => `\x1b[33m${s}\x1b[0m`,
};

// ── Helpers ─────────────────────────────────────────────────────────────────
function askVisible(prompt) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(r => rl.question(prompt, a => { rl.close(); r(a); }));
}


function httpRequest({ method = 'GET', url, headers = {}, body = null }) {
  const u = new URL(url);
  const opts = {
    method,
    hostname: u.hostname,
    path: u.pathname + u.search,
    headers: { ...headers },
  };
  if (body) opts.headers['Content-Length'] = Buffer.byteLength(body);
  return new Promise((resolve, reject) => {
    const req = https.request(opts, res => {
      const chunks = [];
      res.on('data', d => chunks.push(d));
      res.on('end', () => resolve({
        status: res.statusCode,
        headers: res.headers,
        body: Buffer.concat(chunks).toString('utf-8'),
      }));
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

function openBrowser(url) {
  const platform = process.platform;
  let cmd, args;
  if (platform === 'darwin') { cmd = 'open'; args = [url]; }
  else if (platform === 'win32') { cmd = 'cmd'; args = ['/c', 'start', '', url]; }
  else { cmd = 'xdg-open'; args = [url]; }
  try {
    const child = spawn(cmd, args, { detached: true, stdio: 'ignore' });
    child.unref();
    return true;
  } catch (e) {
    return false;
  }
}

function extractCode(input) {
  const s = input.trim();
  if (!s) return '';
  if (s.startsWith('http')) {
    try {
      const u = new URL(s);
      return u.searchParams.get('code') || '';
    } catch (e) { return ''; }
  }
  // 也兼容用户粘 "?code=xxx" 或 "code=xxx"
  const m = s.match(/(?:[?&])?code=([^&\s]+)/);
  if (m) return m[1];
  return s;
}

// ── API wrappers ────────────────────────────────────────────────────────────
async function exchangeCode({ appKey, appSecret, redirectUri, code }) {
  const params = new URLSearchParams({
    app_key: appKey, app_secret: appSecret,
    grant_type: 'authorization_code',
    redirect_uri: redirectUri, code, format: 'json',
  });
  const res = await httpRequest({
    method: 'GET',
    url: `${MINGDAO_API}/oauth2/access_token?${params.toString()}`,
  });
  let json;
  try { json = JSON.parse(res.body); } catch (e) { throw new Error(`access_token 响应不是 JSON: ${res.body.slice(0, 200)}`); }
  if (!json?.success || !json?.access_token) {
    throw new Error(`换取 access_token 失败: ${JSON.stringify(json).slice(0, 300)}`);
  }
  return json;
}

function writeEnv({ appKey, appSecret, callbackUrl }) {
  fs.mkdirSync(CONFIG_DIR, { recursive: true });
  const content = `# oldoa-mcp credentials — generated by create_app.js on ${new Date().toISOString()}\n`
    + `MINGDAO_APP_KEY=${appKey}\n`
    + `MINGDAO_APP_SECRET=${appSecret}\n`
    + `MINGDAO_REDIRECT_URI=${callbackUrl}\n`;
  fs.writeFileSync(ENV_FILE, content, { mode: 0o600 });
}

function parseEnvFile(path) {
  if (!fs.existsSync(path)) return null;
  const out = {};
  for (const line of fs.readFileSync(path, 'utf-8').split('\n')) {
    const m = line.match(/^([A-Z_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim();
  }
  return out;
}

function writeSecrets({ appKey, appSecret, redirectUri, resp }) {
  const now = Math.floor(Date.now() / 1000);
  const expiresIn = parseInt(resp.expires_in || 0, 10) || 0;
  const data = {
    app_key: appKey,
    app_secret: appSecret,
    redirect_uri: redirectUri,
    access_token: resp.access_token,
    refresh_token: resp.refresh_token || '',
    expires_in: resp.expires_in || '',
    issued_at: now,
    expires_at: now + expiresIn,
  };
  fs.writeFileSync(SECRETS_FILE, JSON.stringify(data, null, 2), { mode: 0o600 });
}

// ── Main ────────────────────────────────────────────────────────────────────
(async () => {
  console.log('');
  console.log(c.bold(c.cyan('◆ oldoa-mcp — OAuth 授权配置')));
  console.log(c.dim('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'));
  console.log(`使用共享应用 ${c.bold(FIXED_APP_NAME)}（APP_KEY: ${c.dim(FIXED_APP_KEY)}）`);
  console.log(c.dim('无需自建应用，直接走 OAuth 授权即可。\n'));

  // 检测 .env 是否已有匹配的凭据
  const existingEnv = parseEnvFile(ENV_FILE);
  const needsSecret = !existingEnv
    || existingEnv.MINGDAO_APP_KEY !== FIXED_APP_KEY
    || !existingEnv.MINGDAO_APP_SECRET;

  let appKey = FIXED_APP_KEY;
  let appSecret, callbackUrl;

  if (needsSecret) {
    console.log(c.yellow(`首次配置：需要输入 ${FIXED_APP_NAME} 的 APP_SECRET`));
    console.log(c.dim('（APP_SECRET 只存在本机 ~/.config/oldoa/.env，不上传不落日志）\n'));
    try {
      appSecret = (await askVisible('请输入 APP_SECRET: ')).trim();
      callbackUrl = (await askVisible(`OAuth 回调 URL [默认: ${DEFAULT_CALLBACK_URL}]: `)).trim() || DEFAULT_CALLBACK_URL;
    } catch (e) {
      console.log(c.red('\n已取消。'));
      process.exit(1);
    }
    if (!appSecret) { console.log(c.red('APP_SECRET 不能为空。')); process.exit(1); }
    writeEnv({ appKey, appSecret, callbackUrl });
    console.log(c.green(`✔ .env 已写入 ${ENV_FILE}\n`));
  } else {
    appSecret = existingEnv.MINGDAO_APP_SECRET;
    callbackUrl = existingEnv.MINGDAO_REDIRECT_URI || DEFAULT_CALLBACK_URL;
    console.log(c.green('✔ 已有凭据，直接跑 OAuth 授权'));
    console.log(c.dim(`  APP_KEY:  ${appKey}`));
    console.log(c.dim(`  Callback: ${callbackUrl}\n`));
  }

  // ── OAuth ────────────────────────────────────────────────────────────
  const authUrl = `${MINGDAO_API}/oauth2/authorize?` + new URLSearchParams({
    app_key: appKey, redirect_uri: callbackUrl, state: 'mcp-auth',
  }).toString();

  console.log(c.dim('[1/2] 浏览器授权'));
  const opened = openBrowser(authUrl);
  if (opened) {
    console.log(c.dim('  已尝试自动打开浏览器。如未弹出，手动访问：'));
  } else {
    console.log(c.dim('  无法自动打开浏览器，请手动访问：'));
  }
  console.log('  ' + c.cyan(authUrl));
  console.log('');
  console.log('  浏览器里：');
  console.log('    1. 登录（如未登录）');
  console.log('    2. 点 ' + c.bold('"同意授权"'));
  console.log(`    3. 会跳转到 ${callbackUrl}?code=XXXXXX&state=mcp-auth`);
  console.log(c.dim('       （页面 404 没关系，只需要地址栏的 code= 后那串）'));
  console.log('');

  let code;
  try {
    const raw = await askVisible(c.bold('粘贴 code（支持直接粘整个 URL）: '));
    code = extractCode(raw);
  } catch (e) {
    console.log(c.red('已取消。'));
    process.exit(1);
  }
  if (!code) {
    console.log(c.red('code 解析为空，请重试。'));
    process.exit(1);
  }

  try {
    process.stdout.write(c.dim('[2/2] 换取 access_token ...'));
    const resp = await exchangeCode({ appKey, appSecret, redirectUri: callbackUrl, code });
    writeSecrets({ appKey, appSecret, redirectUri: callbackUrl, resp });
    const expMin = Math.round((parseInt(resp.expires_in || 0, 10) || 0) / 60);
    process.stdout.write(`\r${c.green('[2/2] ✔')} access_token 已保存 ${c.dim(`(${expMin} 分钟有效，自动 refresh)`)}${' '.repeat(5)}\n`);
  } catch (e) {
    console.log('');
    console.log(c.red(`✘ ${e.message}`));
    console.log(c.dim('\ncode 可能过期（每个 code 只用一次，几分钟内有效），请重跑脚本。'));
    process.exit(2);
  }

  console.log('');
  console.log(c.bold(c.green('✅ oldoa-mcp 全部就绪')));
  console.log('');
  console.log('配置文件：');
  console.log(`  ${c.dim(ENV_FILE)}`);
  console.log(`  ${c.dim(SECRETS_FILE)}`);
  console.log('');
  console.log(c.bold('直接启动 Claude Code，oldoa MCP 就能用了。'));
  console.log('');
})().catch(e => {
  console.error(c.red('\n脚本异常：'), e);
  process.exit(1);
});
